// Nomes temáticos exibidos abaixo do nome real do produto (na ficha e no carrinho).
// Cada tipo tem uma lista: itens do mesmo tipo no cardápio recebem apelidos diferentes, em sequência.
// Regras: o apelido dá o clima do tema, mas deixa claro o que é o item (de preferência citando-o),
// e não afirma nada que o tipo não garante (ex.: "fruta" não vira "maçã").

export const APELIDOS = {
  bruxo: {
    suco_laranja: ['Poção de Laranja do Sol Nascente', 'Elixir Dourado de Laranja'],
    suco_uva: ['Elixir de Uva do Crepúsculo', 'Poção das Videiras Sombrias'],
    suco_limao: ['Poção Cítrica de Limão', 'Tônico de Limão do Boticário'],
    suco_morango: ['Poção de Morango Encantado', 'Tônico Rubi de Morango'],
    suco_maracuja: ['Poção de Maracujá da Calmaria', 'Elixir de Maracujá do Sono Leve'],
    suco_abacaxi: ['Poção de Abacaxi da Coroa Dourada', 'Elixir Tropical de Abacaxi'],
    suco_melancia: ['Poção de Melancia da Lua Carmesim', 'Tônico Refrescante de Melancia'],
    suco_manga: ['Elixir de Manga do Pôr do Sol', 'Poção Dourada de Manga'],
    suco_detox: ['Poção Verde Purificadora', 'Tônico Verde da Estufa'],
    refrigerante_cola: ['Refresco Borbulhante das Sombras', 'Poção Efervescente da Meia-Noite'],
    refrigerante_guarana: ['Guaraná de Fogo-Fátuo', 'Refresco Âmbar Borbulhante'],
    refrigerante_laranja: ['Refresco de Laranja da Fênix', 'Laranja Efervescente do Entardecer'],
    refrigerante_limao: ['Refresco de Limão Efervescente', 'Limão Borbulhante do Pântano'],
    refrigerante_uva: ['Refresco de Uva Borbulhante', 'Uva Efervescente do Crepúsculo'],
    energetico: ['Poção Energética do Relâmpago', 'Elixir da Vigília Eterna'],
    cha_gelado: ['Chá Gelado da Vidente', 'Infusão Gelada Enfeitiçada'],
    agua: ['Água da Fonte Encantada', 'Água do Lago Cristalino'],
    agua_gas: ['Água Cintilante da Nascente', 'Água Borbulhante Encantada'],
    agua_coco: ['Água do Coqueiro Encantado', 'Água de Coco das Ilhas Mágicas'],
    cerveja: ['Cerveja do Caldeirão', 'Cerveja Espumante do Salão', 'Caneca Espumante do Mago'],
    cerveja_escura: ['Cerveja das Sombras', 'Cerveja Escura do Caldeirão'],
    vinho: ['Vinho da Adega Encantada', 'Vinho do Filtro do Amor'],
    vinho_branco: ['Vinho Pálido da Lua', 'Vinho das Videiras de Prata'],
    drink: ['Drink do Alquimista', 'Coquetel da Festa Encantada', 'Mistura Enfeitiçada'],
    caipirinha: ['Caipirinha do Alquimista', 'Caipirinha Cítrica da Floresta'],
    cafe: ['Café Elixir do Despertar', 'Café Negro da Madrugada'],
    cappuccino: ['Cappuccino Cremoso Encantado', 'Nuvem de Café Encantado'],
    cha: ['Chá da Vidente', 'Chá das Folhas Proféticas'],
    chocolate_quente: ['Cacau Quente contra Calafrios', 'Poção Quente de Chocolate'],
    milkshake: ['Milkshake Nuvem de Fada', 'Milkshake Encantado do Unicórnio'],
    smoothie: ['Smoothie das Frutas Silvestres', 'Poção Batida do Bosque'],
    vitamina: ['Vitamina da Força Matinal', 'Vitamina Revigorante do Pomar'],

    hamburguer: ['Hambúrguer Alado', 'Hambúrguer do Dragão', 'Hambúrguer Enfeitiçado'],
    hotdog: ['Cachorro-quente da Salamandra', 'Cachorro-quente Flamejante'],
    pizza: ['Pizza Rúnica', 'Pizza do Forno Encantado'],
    batata_frita: ['Batatas do Caldeirão', 'Fritas Encantadas'],
    frango: ['Frango do Grifo', 'Frango Encantado'],
    carne: ['Carne do Banquete Encantado', 'Carne Grelhada do Salão'],
    peixe: ['Peixe do Lago Encantado', 'Peixe do Lago Escuro'],
    camarao: ['Camarões do Lago das Sereias', 'Camarões Encantados'],
    salada: ['Salada da Estufa Mágica', 'Salada de Ervas da Estufa'],
    sopa: ['Caldo do Caldeirão Mirim', 'Sopa Borbulhante'],
    massa: ['Massa Enfeitiçada', 'Massa do Caldeirão'],
    lasanha: ['Lasanha das Mil Camadas', 'Lasanha do Forno Encantado'],
    prato_feito: ['Prato do Salão Principal', 'Prato do Aprendiz de Feiticeiro'],
    sanduiche: ['Sanduíche do Aprendiz', 'Sanduíche Enfeitiçado'],
    wrap: ['Wrap Enrolado como Pergaminho', 'Rolo Recheado do Escriba'],
    porcao: ['Petiscos do Caldeirão', 'Porção do Alquimista'],
    pastel: ['Pastel Encantado', 'Pastel do Caldeirão'],
    coxinha: ['Coxinha Encantada', 'Coxinha do Caldeirão'],
    pao_de_queijo: ['Pães de Queijo Encantados', 'Pão de Queijo do Forno Mágico'],
    sushi: ['Sushi do Lago Encantado', 'Sushi do Mestre das Águas'],
    temaki: ['Temaki Enfeitiçado', 'Cone de Alga Encantado'],
    espetinho: ['Espetinho da Varinha', 'Espetinho do Mago'],
    croissant: ['Croissant da Lua Crescente', 'Croissant Folhado Encantado'],

    bolo: ['Bolo das Velas Eternas', 'Bolo Enfeitiçado'],
    cupcake: ['Cupcake da Fada Madrinha', 'Cupcake Enfeitiçado'],
    sorvete: ['Sorvete Enfeitiçado', 'Sorvete das Neves Eternas'],
    picole: ['Picolé Enfeitiçado', 'Picolé Congelado por Feitiço'],
    pudim: ['Pudim Levitante', 'Pudim Flutuante do Salão'],
    mousse: ['Mousse Encantada na Taça', 'Mousse Nuvem Doce'],
    torta: ['Torta do Salão Encantado', 'Torta Enfeitiçada'],
    cookie: ['Cookie Estelar', 'Cookie das Estrelas'],
    chocolate: ['Chocolate Enfeitiçado', 'Doce de Cacau do Boticário'],
    brigadeiro: ['Brigadeiros Encantados', 'Docinhos do Caldeirão'],
    churros: ['Churros do Mago', 'Churros Encantados'],
    waffle: ['Waffle do Castelo', 'Waffle Dourado Encantado'],
    acai: ['Açaí do Bosque Encantado', 'Açaí Roxo da Floresta'],
    donut: ['Rosquinha Encantada', 'Rosquinha Anel de Fada'],
    fruta: ['Frutas da Árvore Encantada', 'Frutas do Pomar Mágico'],
    generico: ['Mistério Encantado', 'Prato Enfeitiçado', 'Surpresa do Caldeirão'],
  },

  medieval: {
    suco_laranja: ['Suco de Laranja do Pomar Real', 'Néctar de Laranja do Castelo'],
    suco_uva: ['Suco de Uva do Vale', 'Suco da Vinha do Mosteiro'],
    suco_limao: ['Limonada do Boticário', 'Refresco de Limão da Corte'],
    suco_morango: ['Néctar de Morangos Silvestres', 'Suco de Morango da Donzela'],
    suco_maracuja: ['Néctar de Maracujá das Terras do Sul', 'Suco de Maracujá do Mercador'],
    suco_abacaxi: ['Suco de Abacaxi do Pomar Real', 'Néctar de Abacaxi do Mercador'],
    suco_melancia: ['Suco de Melancia da Colheita', 'Refresco de Melancia do Horto'],
    suco_manga: ['Néctar de Manga do Mercador', 'Suco de Manga das Terras do Sul'],
    suco_detox: ['Suco Verde do Herbalista', 'Suco Verde do Mosteiro'],
    refrigerante_cola: ['Refresco Borbulhante Escuro', 'Borbulha Negra da Taverna'],
    refrigerante_guarana: ['Guaraná Borbulhante da Taverna', 'Refresco Borbulhante Dourado'],
    refrigerante_laranja: ['Refresco Borbulhante de Laranja', 'Laranja Borbulhante do Pomar'],
    refrigerante_limao: ['Refresco Borbulhante de Limão', 'Limão Borbulhante da Corte'],
    refrigerante_uva: ['Refresco Borbulhante de Uva', 'Uva Borbulhante do Rei'],
    energetico: ['Elixir do Cavaleiro Incansável', 'Tônico Energético do Guarda Noturno'],
    cha_gelado: ['Chá Gelado do Poço', 'Chá Frio do Herbalista'],
    agua: ['Água da Fonte do Castelo', 'Água do Poço Real'],
    agua_gas: ['Água da Fonte Borbulhante', 'Água Borbulhante das Termas'],
    agua_coco: ['Água de Coco dos Navegantes', 'Água do Fruto das Ilhas'],
    cerveja: ['Cerveja do Mosteiro', 'Caneca de Cerveja do Taverneiro', 'Cerveja da Guilda'],
    cerveja_escura: ['Cerveja Escura do Ferreiro', 'Caneca de Cerveja Negra'],
    vinho: ['Vinho da Adega Real', 'Taça de Vinho do Rei'],
    vinho_branco: ['Vinho Claro da Abadia', 'Taça Dourada da Rainha'],
    drink: ['Chifre do Guerreiro', 'Drink do Bardo', 'Mistura da Taverna'],
    caipirinha: ['Caipirinha do Marinheiro', 'Caipirinha do Engenho'],
    cafe: ['Café Negro do Vigia', 'Café da Sentinela'],
    cappuccino: ['Café com Nata do Vigia', 'Cappuccino da Sentinela'],
    cha: ['Chá do Herbalista', 'Chá das Ervas do Mosteiro'],
    chocolate_quente: ['Chocolate Quente do Mercador', 'Cacau Quente das Terras Distantes'],
    milkshake: ['Milkshake da Leiteira', 'Leite Batido da Fazenda'],
    smoothie: ['Batida de Frutas do Bosque', 'Smoothie das Frutas Silvestres'],
    vitamina: ['Vitamina do Camponês', 'Vitamina do Lavrador'],

    hamburguer: ['Hambúrguer do Torneio', 'Hambúrguer do Escudeiro', 'Lanche do Cavaleiro'],
    hotdog: ['Cachorro-quente da Feira', 'Salsicha do Açougueiro no Pão'],
    pizza: ['Pizza do Forno a Lenha', 'Pizza do Forno do Castelo'],
    batata_frita: ['Batatas Fritas da Taverna', 'Batatas da Colheita'],
    frango: ['Frango do Galinheiro Real', 'Frango do Banquete'],
    carne: ['Carne do Braseiro Real', 'Carne Grelhada do Banquete'],
    peixe: ['Peixe do Rio do Castelo', 'Peixe do Porto da Vila'],
    camarao: ['Camarões do Porto', 'Frutos do Mar do Mercador'],
    salada: ['Salada da Horta', 'Folhas do Jardim do Mosteiro'],
    sopa: ['Caldo Quente da Estalagem', 'Sopa do Caldeirão da Taverna'],
    massa: ['Massa do Mercador', 'Massa do Moinho'],
    lasanha: ['Lasanha do Forno de Pedra', 'Lasanha da Abadia'],
    prato_feito: ['Refeição do Camponês', 'Prato do Viajante'],
    sanduiche: ['Sanduíche do Moleiro', 'Sanduíche do Peregrino'],
    wrap: ['Pão Enrolado do Viajante', 'Rolo Recheado do Mensageiro'],
    porcao: ['Petiscos da Taverna', 'Porção da Guilda'],
    pastel: ['Pastel da Feira', 'Empanada do Peregrino'],
    coxinha: ['Coxinha da Feira da Vila', 'Coxinha do Padeiro'],
    pao_de_queijo: ['Pão de Queijo do Forno de Pedra', 'Pãezinhos de Queijo da Fazenda'],
    sushi: ['Sushi do Mercador Oriental', 'Sushi das Terras do Leste'],
    temaki: ['Temaki do Mercador Oriental', 'Cone de Alga das Terras do Leste'],
    espetinho: ['Espetinho da Fogueira', 'Espeto do Ferreiro'],
    croissant: ['Croissant do Padeiro Real', 'Croissant Folhado da Corte'],

    bolo: ['Bolo da Festa da Colheita', 'Bolo do Banquete Real'],
    cupcake: ['Cupcake da Princesa', 'Bolinho Confeitado da Feira'],
    sorvete: ['Sorvete da Montanha Nevada', 'Sorvete do Inverno'],
    picole: ['Picolé do Inverno', 'Picolé do Mercador'],
    pudim: ['Pudim do Mosteiro', 'Pudim da Abadia'],
    mousse: ['Mousse da Corte na Taça', 'Taça de Mousse da Rainha'],
    torta: ['Torta da Colheita', 'Torta do Forno de Pedra'],
    cookie: ['Biscoito do Padeiro Real', 'Cookie do Peregrino'],
    chocolate: ['Doce de Cacau do Mercador', 'Chocolate do Tesouro Real'],
    brigadeiro: ['Brigadeiros da Corte', 'Docinhos do Tesouro Real'],
    churros: ['Churros da Feira', 'Churros do Festival'],
    waffle: ['Waffle do Padeiro Real', 'Waffle da Padaria do Castelo'],
    acai: ['Açaí do Bosque', 'Tigela de Açaí Selvagem'],
    donut: ['Rosquinha da Feira', 'Rosca Açucarada da Padaria'],
    fruta: ['Frutas do Pomar Real', 'Cesta de Frutas da Colheita'],
    generico: ['Surpresa do Taverneiro', 'Prato da Casa', 'Segredo da Cozinha'],
  },

  futurista: {
    suco_laranja: ['Cápsula de Laranja C-12', 'Suco de Laranja Concentrado'],
    suco_uva: ['Cápsula de Uva V-7', 'Suco de Uva Hidropônica'],
    suco_limao: ['Cápsula de Limão L-3', 'Limonada de Estufa Orbital'],
    suco_morango: ['Cápsula de Morango R-9', 'Suco de Morango Sintético'],
    suco_maracuja: ['Cápsula de Maracujá M-5', 'Suco de Maracujá Calmante'],
    suco_abacaxi: ['Cápsula de Abacaxi T-4', 'Suco de Abacaxi de Estufa'],
    suco_melancia: ['Cápsula de Melancia H-8', 'Suco de Melancia Hidratante'],
    suco_manga: ['Cápsula de Manga A-6', 'Suco de Manga Orbital'],
    suco_detox: ['Cápsula Verde Detox D-1', 'Suco Verde Biorregenerador'],
    refrigerante_cola: ['Neo Cola Gravidade Zero', 'Cola Quântica'],
    refrigerante_guarana: ['Guaraná Quântico', 'Guaraná Iônico'],
    refrigerante_laranja: ['Laranja Fizz de Plasma', 'Refri de Laranja Orbital'],
    refrigerante_limao: ['Limão Fizz Iônico', 'Refri de Limão Neon'],
    refrigerante_uva: ['Uva Fizz Nebular', 'Refri de Uva Iônico'],
    energetico: ['Energético Carga de Reator', 'Bateria Líquida Mk III'],
    cha_gelado: ['Chá Gelado Criogênico', 'Chá Resfriado a Nitrogênio'],
    agua: ['Água Filtrada de Cometa', 'Água de Degelo Polar'],
    agua_gas: ['Água Ionizada com Gás', 'Água Gaseificada Orbital'],
    agua_coco: ['Água de Coco de Estufa', 'Água de Coco Hidratante'],
    cerveja: ['Cerveja Orbital', 'Cerveja de Estação Espacial'],
    cerveja_escura: ['Cerveja de Matéria Escura', 'Cerveja Buraco Negro'],
    vinho: ['Vinho Sintético Safra 2199', 'Vinho Fermentado em Órbita'],
    vinho_branco: ['Vinho Branco de Estufa Lunar', 'Espumante Safra 2199'],
    drink: ['Drink Nebulosa Líquida', 'Coquetel de Hiperespaço', 'Drink Estelar'],
    caipirinha: ['Caipirinha Supernova', 'Caipirinha Estelar'],
    cafe: ['Café Hiperpropulsão', 'Café Combustível de Piloto'],
    cappuccino: ['Cappuccino Hiperpropulsão', 'Nuvem de Café Pressurizada'],
    cha: ['Chá Bioluminescente', 'Chá de Estufa Orbital'],
    chocolate_quente: ['Chocolate Termonuclear', 'Cacau Aquecido a Plasma'],
    milkshake: ['Milkshake Criogênico', 'Milkshake Gravidade Zero'],
    smoothie: ['Smoothie de Frutas Replicadas', 'Smoothie Bioativo'],
    vitamina: ['Vitamina Matinal Mk I', 'Vitamina Nutritiva de Bordo'],

    hamburguer: ['Burger Holográfico Mk II', 'Burger Replicado', 'Hambúrguer de Proteína Cultivada'],
    hotdog: ['Cachorro-quente de Plasma', 'Hot Dog de Fusão'],
    pizza: ['Pizza Replicada', 'Pizza do Forno de Plasma'],
    batata_frita: ['Batatas Fritas Hidropônicas', 'Bastões de Batata Crocante'],
    frango: ['Frango Cultivado em Laboratório', 'Frango Grelhado a Laser'],
    carne: ['Carne Grelhada a Laser', 'Corte Premium Cultivado'],
    peixe: ['Peixe do Aquário Orbital', 'Peixe de Biotanque'],
    camarao: ['Camarões do Biotanque', 'Frutos do Mar Orbitais'],
    salada: ['Salada Hidropônica', 'Mix de Folhas de Estufa'],
    sopa: ['Caldo Térmico', 'Sopa Pressurizada'],
    massa: ['Massa Replicada', 'Massa Extrudada Orbital'],
    lasanha: ['Lasanha Impressa em Camadas', 'Lasanha Gratinada a Plasma'],
    prato_feito: ['Refeição Completa de Tripulante', 'Prato Executivo de Bordo'],
    sanduiche: ['Sanduíche de Bordo', 'Módulo Sanduíche'],
    wrap: ['Wrap de Bordo', 'Wrap Nutritivo Selado'],
    porcao: ['Kit Petisco Tático', 'Porção da Tripulação'],
    pastel: ['Pastel Selado a Vácuo', 'Pastel Crocante Pressurizado'],
    coxinha: ['Coxinha Mk I', 'Coxinha Crocante Orbital'],
    pao_de_queijo: ['Pão de Queijo Aquecido a Plasma', 'Orbes de Pão de Queijo'],
    sushi: ['Kit Sushi de Bordo', 'Sushi de Biotanque'],
    temaki: ['Temaki em Cone Selado', 'Temaki Orbital'],
    espetinho: ['Espetinho de Íons', 'Espetinho Grelhado a Laser'],
    croissant: ['Croissant de Impressão Folhada', 'Croissant Laminado Orbital'],

    bolo: ['Bolo Gravitacional', 'Bolo em Camadas Estabilizadas'],
    cupcake: ['Cupcake de Órbita Baixa', 'Micro-Bolo Decorado'],
    sorvete: ['Sorvete Criogênico', 'Sorvete de Nitrogênio Líquido'],
    picole: ['Picolé Criogênico', 'Picolé de Órbita Polar'],
    pudim: ['Pudim Estabilizado', 'Pudim de Gravidade Controlada'],
    mousse: ['Mousse Pressurizada', 'Mousse Aerada de Bordo'],
    torta: ['Torta de Estufa Lunar', 'Torta do Forno de Plasma'],
    cookie: ['Cookie Asteroide', 'Cookie de Cratera'],
    chocolate: ['Lingotes de Chocolate', 'Barras de Energia de Cacau'],
    brigadeiro: ['Brigadeiros Planetários', 'Esferas de Chocolate Orbitais'],
    churros: ['Churros Extrudados', 'Churros de Açúcar Iônico'],
    waffle: ['Waffle Térmico', 'Waffle Painel Solar'],
    acai: ['Açaí Nebular', 'Açaí Energético'],
    donut: ['Rosquinha de Saturno', 'Rosquinha Anel Orbital'],
    fruta: ['Frutas Hidropônicas', 'Frutas da Estufa Orbital'],
    generico: ['Ração Misteriosa', 'Item Não Identificado', 'Refeição Padrão de Bordo'],
  },
  pirata: {
    suco_laranja: ['Suco de Laranja do Caribe', 'Suco de Laranja do Capitão'],
    suco_uva: ['Suco de Uva de Tortuga', 'Suco de Uva da Bandeira Negra'],
    suco_limao: ['Limonada contra Escorbuto', 'Suco de Limão do Imediato'],
    suco_morango: ['Suco de Morango da Ilha da Caveira', 'Suco de Morango do Corsário'],
    suco_maracuja: ['Suco de Maracujá do Caribe', 'Suco de Maracujá do Papagaio do Capitão'],
    suco_abacaxi: ['Suco de Abacaxi da Ilha do Tesouro', 'Suco de Abacaxi do Caribe'],
    suco_melancia: ['Suco de Melancia da Praia de Tortuga', 'Suco de Melancia do Convés'],
    suco_manga: ['Suco de Manga do Caribe', 'Suco de Manga do Capitão'],
    suco_detox: ['Suco Verde contra Escorbuto', 'Suco Verde do Cozinheiro de Bordo'],
    refrigerante_cola: ['Refrigerante da Bandeira Negra', 'Cola Borbulhante do Kraken'],
    refrigerante_guarana: ['Guaraná do Caribe', 'Guaraná Borbulhante do Convés'],
    refrigerante_laranja: ['Refrigerante de Laranja de Tortuga', 'Laranja Borbulhante da Ilha'],
    refrigerante_limao: ['Refrigerante de Limão do Imediato', 'Limão Borbulhante do Galeão'],
    refrigerante_uva: ['Refrigerante de Uva do Kraken', 'Uva Borbulhante do Corsário'],
    energetico: ['Energético do Vigia do Cesto da Gávea', 'Energético do Timoneiro'],
    cha_gelado: ['Chá Gelado do Convés', 'Chá Gelado do Capitão'],
    agua: ['Água Doce do Cantil', 'Água do Cantil do Marujo'],
    agua_gas: ['Água com Gás de Tortuga', 'Água Borbulhante de Bordo'],
    agua_coco: ['Água de Coco da Ilha Deserta', 'Água de Coco do Náufrago'],
    cerveja: ['Cerveja de Tortuga', 'Caneca da Tripulação', 'Cerveja do Corsário'],
    cerveja_escura: ['Cerveja Escura do Kraken', 'Cerveja Negra do Holandês Voador'],
    vinho: ['Vinho do Tesouro do Capitão', 'Vinho do Porão do Galeão'],
    vinho_branco: ['Vinho Branco do Porto', 'Espumante do Baú do Tesouro'],
    drink: ['Drink do Caribe', 'Coquetel da Bandeira Negra', 'Drink do Capitão'],
    caipirinha: ['Caipirinha de Tortuga', 'Caipirinha do Marujo'],
    cafe: ['Café do Cesto da Gávea', 'Café Forte do Timoneiro'],
    cappuccino: ['Cappuccino do Capitão', 'Café Cremoso de Bordo'],
    cha: ['Chá do Imediato', 'Chá Quente da Cabine do Capitão'],
    chocolate_quente: ['Chocolate Quente da Cabine', 'Chocolate Quente do Grumete'],
    milkshake: ['Milkshake do Grumete', 'Milkshake do Caribe'],
    smoothie: ['Smoothie das Frutas do Caribe', 'Smoothie do Náufrago'],
    vitamina: ['Vitamina do Marujo', 'Vitamina do Grumete'],

    hamburguer: ['Hambúrguer do Capitão', 'Hambúrguer da Bandeira Negra', 'Hambúrguer do Kraken'],
    hotdog: ['Cachorro-quente do Convés', 'Cachorro-quente do Marujo'],
    pizza: ['Pizza da Ilha da Caveira', 'Pizza de Tortuga'],
    batata_frita: ['Batatas Fritas do Galeão', 'Batatas da Tripulação'],
    frango: ['Frango do Capitão', 'Frango da Cozinha de Bordo'],
    carne: ['Carne do Banquete do Capitão', 'Carne Grelhada de Tortuga'],
    peixe: ['Peixe dos Sete Mares', 'Peixe Pescado do Convés'],
    camarao: ['Camarões dos Sete Mares', 'Camarões da Rede do Pescador'],
    salada: ['Salada da Ilha do Tesouro', 'Salada Fresca do Porto'],
    sopa: ['Sopa da Cozinha de Bordo', 'Caldo do Caldeirão do Navio'],
    massa: ['Massa Tentáculos do Kraken', 'Massa do Cozinheiro de Bordo'],
    lasanha: ['Lasanha do Capitão', 'Lasanha do Galeão'],
    prato_feito: ['Prato do Marujo', 'Refeição da Tripulação'],
    sanduiche: ['Sanduíche do Grumete', 'Sanduíche de Bordo'],
    wrap: ['Wrap Enrolado como Mapa do Tesouro', 'Wrap do Marujo'],
    porcao: ['Petiscos da Tripulação', 'Porção de Tortuga'],
    pastel: ['Pastel do Porto', 'Pastel do Grumete'],
    coxinha: ['Coxinha do Convés', 'Coxinha da Tripulação'],
    pao_de_queijo: ['Pães de Queijo Bala de Canhão', 'Pão de Queijo do Cozinheiro de Bordo'],
    sushi: ['Sushi dos Sete Mares', 'Sushi do Pescador'],
    temaki: ['Temaki dos Sete Mares', 'Temaki do Pescador'],
    espetinho: ['Espetinho na Espada Pirata', 'Espetinho do Convés'],
    croissant: ['Croissant do Porto', 'Croissant da Cabine do Capitão'],

    bolo: ['Bolo do Baú do Tesouro', 'Bolo do Capitão'],
    cupcake: ['Cupcake do Grumete', 'Cupcake do Tesouro'],
    sorvete: ['Sorvete do Caribe', 'Sorvete do Capitão'],
    picole: ['Picolé do Convés', 'Picolé da Praia de Tortuga'],
    pudim: ['Pudim do Cozinheiro de Bordo', 'Pudim do Capitão'],
    mousse: ['Mousse na Taça do Capitão', 'Mousse do Tesouro'],
    torta: ['Torta de Tortuga', 'Torta da Cozinha de Bordo'],
    cookie: ['Cookie Moeda de Ouro', 'Cookie do Grumete'],
    chocolate: ['Chocolate do Baú do Tesouro', 'Chocolate do Capitão'],
    brigadeiro: ['Brigadeiros Bala de Canhão', 'Brigadeiros do Tesouro'],
    churros: ['Churros do Porto', 'Churros da Tripulação'],
    waffle: ['Waffle do Capitão', 'Waffle da Cabine'],
    acai: ['Açaí do Caribe', 'Açaí do Náufrago'],
    donut: ['Rosquinha Boia Salva-vidas', 'Rosquinha de Tortuga'],
    fruta: ['Frutas da Ilha do Tesouro', 'Frutas do Caribe'],
    generico: ['Surpresa do Baú do Tesouro', 'Prato do Cozinheiro de Bordo', 'Mistério dos Sete Mares'],
  },

  faroeste: {
    suco_laranja: ['Suco de Laranja do Xerife', 'Suco de Laranja do Rancho'],
    suco_uva: ['Suco de Uva do Saloon', 'Suco de Uva do Fora da Lei'],
    suco_limao: ['Limonada do Saloon', 'Limonada do Delegado'],
    suco_morango: ['Suco de Morango do Rancho', 'Suco de Morango da Diligência'],
    suco_maracuja: ['Suco de Maracujá do Forasteiro', 'Suco de Maracujá da Estação de Trem'],
    suco_abacaxi: ['Suco de Abacaxi do Saloon', 'Suco de Abacaxi da Fronteira'],
    suco_melancia: ['Suco de Melancia do Rancho', 'Suco de Melancia do Deserto'],
    suco_manga: ['Suco de Manga da Fronteira', 'Suco de Manga do Pistoleiro'],
    suco_detox: ['Suco Verde da Horta do Rancho', 'Suco Verde do Delegado'],
    refrigerante_cola: ['Refrigerante de Cola do Saloon', 'Cola Gelada do Xerife'],
    refrigerante_guarana: ['Guaraná do Fora da Lei', 'Guaraná Gelado da Fronteira'],
    refrigerante_laranja: ['Refrigerante de Laranja do Saloon', 'Laranja Gelada da Estação de Trem'],
    refrigerante_limao: ['Refrigerante de Limão do Delegado', 'Limão Gelado do Deserto'],
    refrigerante_uva: ['Refrigerante de Uva do Bando', 'Uva Gelada da Diligência'],
    energetico: ['Energético Banana de Dinamite', 'Energético do Pistoleiro'],
    cha_gelado: ['Chá Gelado do Alpendre', 'Chá Gelado do Rancho'],
    agua: ['Água do Cantil do Caubói', 'Água da Caixa-d’Água da Ferrovia'],
    agua_gas: ['Água com Gás do Saloon', 'Água Borbulhante da Fonte'],
    agua_coco: ['Água de Coco do Forasteiro', 'Água de Coco Gelada do Saloon'],
    cerveja: ['Cerveja do Saloon', 'Caneca do Xerife', 'Cerveja do Fora da Lei'],
    cerveja_escura: ['Cerveja Escura do Garimpeiro', 'Cerveja Escura da Mina de Ouro'],
    vinho: ['Vinho da Fronteira', 'Vinho do Rancho'],
    vinho_branco: ['Vinho Branco do Saloon', 'Espumante da Corrida do Ouro'],
    drink: ['Drink do Pistoleiro', 'Coquetel do Fora da Lei', 'Drink do Saloon'],
    caipirinha: ['Caipirinha do Saloon', 'Caipirinha do Bando'],
    cafe: ['Café de Fogueira do Caubói', 'Café Forte do Xerife'],
    cappuccino: ['Cappuccino do Saloon', 'Café Cremoso do Rancho'],
    cha: ['Chá do Alpendre', 'Chá Quente da Estação de Trem'],
    chocolate_quente: ['Chocolate Quente da Fogueira', 'Chocolate Quente do Rancho'],
    milkshake: ['Milkshake da Fazenda', 'Milkshake do Saloon'],
    smoothie: ['Smoothie do Rancho', 'Smoothie da Fronteira'],
    vitamina: ['Vitamina do Vaqueiro', 'Vitamina do Rancho'],

    hamburguer: ['Hambúrguer do Xerife', 'Hambúrguer Procurado Vivo ou Morto', 'Hambúrguer do Fora da Lei'],
    hotdog: ['Cachorro-quente da Diligência', 'Cachorro-quente do Vagão-Restaurante'],
    pizza: ['Pizza do Saloon', 'Pizza do Bando'],
    batata_frita: ['Batatas Fritas do Saloon', 'Batatas do Rancho'],
    frango: ['Frango do Rancho', 'Frango na Brasa da Fronteira'],
    carne: ['Bife do Rancho', 'Carne na Brasa do Xerife'],
    peixe: ['Peixe do Rio Grande', 'Peixe do Riacho do Rancho'],
    camarao: ['Camarões da Costa Oeste', 'Camarões do Vagão-Restaurante'],
    salada: ['Salada da Horta do Rancho', 'Salada do Saloon'],
    sopa: ['Sopa da Fogueira', 'Caldo Quente do Acampamento do Bando'],
    massa: ['Massa do Saloon', 'Massa do Vagão-Restaurante'],
    lasanha: ['Lasanha do Rancho', 'Lasanha do Saloon'],
    prato_feito: ['Prato do Vaqueiro', 'Refeição do Forasteiro'],
    sanduiche: ['Sanduíche da Diligência', 'Sanduíche do Trem das Onze'],
    wrap: ['Wrap da Fronteira', 'Wrap do Fora da Lei'],
    porcao: ['Petiscos do Saloon', 'Porção do Balcão do Xerife'],
    pastel: ['Pastel da Estação de Trem', 'Pastel do Saloon'],
    coxinha: ['Coxinha do Saloon', 'Coxinha do Rancho'],
    pao_de_queijo: ['Pão de Queijo do Rancho', 'Pepitas de Pão de Queijo'],
    sushi: ['Sushi da Costa Oeste', 'Sushi do Forasteiro'],
    temaki: ['Temaki da Costa Oeste', 'Temaki do Forasteiro'],
    espetinho: ['Espetinho da Fogueira', 'Espetinho do Vaqueiro'],
    croissant: ['Croissant do Saloon', 'Croissant da Estação de Trem'],

    bolo: ['Bolo da Vovó do Rancho', 'Bolo do Saloon'],
    cupcake: ['Cupcake da Feira do Condado', 'Cupcake do Saloon'],
    sorvete: ['Sorvete para o Calor do Deserto', 'Sorvete do Saloon'],
    picole: ['Picolé do Deserto', 'Picolé da Estação de Trem'],
    pudim: ['Pudim da Vovó do Rancho', 'Pudim do Saloon'],
    mousse: ['Mousse na Taça do Saloon', 'Mousse do Rancho'],
    torta: ['Torta da Janela do Rancho', 'Torta da Feira do Condado'],
    cookie: ['Cookie do Rancho', 'Cookie da Diligência'],
    chocolate: ['Chocolate do Assalto ao Trem', 'Chocolate do Garimpeiro'],
    brigadeiro: ['Brigadeiros Pepitas da Mina', 'Brigadeiros do Saloon'],
    churros: ['Churros Banana de Dinamite', 'Churros da Fronteira'],
    waffle: ['Waffle do Café da Manhã do Rancho', 'Waffle do Saloon'],
    acai: ['Açaí do Forasteiro', 'Açaí da Fronteira'],
    donut: ['Rosquinha do Xerife', 'Rosquinha do Delegado'],
    fruta: ['Frutas do Rancho', 'Frutas da Feira do Condado'],
    generico: ['Surpresa do Saloon', 'Recompensa do Xerife', 'Mistério da Fronteira'],
  },

  mar: {
    suco_laranja: ['Suco de Laranja do Recife', 'Suco de Laranja da Maré Alta'],
    suco_uva: ['Suco de Uva das Profundezas', 'Suco de Uva da Lagoa Azul'],
    suco_limao: ['Limonada da Maré', 'Limonada do Recife'],
    suco_morango: ['Suco de Morango do Coral', 'Suco de Morango da Sereia'],
    suco_maracuja: ['Suco de Maracujá da Lagoa', 'Suco de Maracujá das Correntes'],
    suco_abacaxi: ['Suco de Abacaxi da Ilha do Recife', 'Suco de Abacaxi da Maré'],
    suco_melancia: ['Suco de Melancia do Coral', 'Suco de Melancia da Praia'],
    suco_manga: ['Suco de Manga da Lagoa Azul', 'Suco de Manga do Recife'],
    suco_detox: ['Suco Verde do Recife', 'Suco Verde da Maré'],
    refrigerante_cola: ['Refrigerante de Cola das Profundezas', 'Cola Borbulhante do Recife'],
    refrigerante_guarana: ['Guaraná Borbulhante do Recife', 'Guaraná da Maré'],
    refrigerante_laranja: ['Refrigerante de Laranja do Coral', 'Laranja Borbulhante da Maré'],
    refrigerante_limao: ['Refrigerante de Limão da Lagoa', 'Limão Borbulhante do Recife'],
    refrigerante_uva: ['Refrigerante de Uva das Profundezas', 'Uva Borbulhante da Sereia'],
    energetico: ['Energético da Enguia Elétrica', 'Energético das Correntes'],
    cha_gelado: ['Chá Gelado da Maré', 'Chá Gelado do Recife'],
    agua: ['Água Cristalina da Lagoa', 'Bolha de Água Pura'],
    agua_gas: ['Água com Gás das Bolhas', 'Água Borbulhante do Recife'],
    agua_coco: ['Água de Coco da Praia', 'Água de Coco da Ilha do Recife'],
    cerveja: ['Cerveja do Recife', 'Caneca das Profundezas', 'Cerveja da Maré'],
    cerveja_escura: ['Cerveja Escura da Fossa Abissal', 'Cerveja Escura das Profundezas'],
    vinho: ['Vinho do Naufrágio', 'Vinho da Adega Submersa'],
    vinho_branco: ['Vinho Branco da Pérola', 'Espumante das Bolhas'],
    drink: ['Drink da Sereia', 'Coquetel do Recife', 'Drink das Correntes'],
    caipirinha: ['Caipirinha da Maré', 'Caipirinha do Recife'],
    cafe: ['Café das Profundezas', 'Café do Farol'],
    cappuccino: ['Cappuccino de Espuma do Mar', 'Cappuccino do Recife'],
    cha: ['Chá da Lagoa Azul', 'Chá Quente do Recife'],
    chocolate_quente: ['Chocolate Quente do Farol', 'Chocolate Quente das Profundezas'],
    milkshake: ['Milkshake de Espuma do Mar', 'Milkshake da Sereia'],
    smoothie: ['Smoothie do Recife de Coral', 'Smoothie da Maré'],
    vitamina: ['Vitamina do Mergulhador', 'Vitamina da Maré'],

    hamburguer: ['Hambúrguer do Recife', 'Hambúrguer das Profundezas', 'Hambúrguer do Mergulhador'],
    hotdog: ['Cachorro-quente do Cais', 'Cachorro-quente da Maré'],
    pizza: ['Pizza do Recife', 'Pizza das Profundezas'],
    batata_frita: ['Batatas Fritas do Cais', 'Batatas da Maré'],
    frango: ['Frango do Farol', 'Frango do Cais'],
    carne: ['Carne Grelhada do Cais', 'Carne do Banquete do Recife'],
    peixe: ['Peixe do Recife', 'Peixe do Cardume'],
    camarao: ['Camarões do Recife', 'Camarões da Maré'],
    salada: ['Salada do Recife', 'Salada da Lagoa'],
    sopa: ['Sopa das Profundezas', 'Caldo Quente do Farol'],
    massa: ['Massa da Sereia', 'Massa do Recife'],
    lasanha: ['Lasanha em Camadas do Recife', 'Lasanha das Profundezas'],
    prato_feito: ['Prato do Mergulhador', 'Refeição do Pescador'],
    sanduiche: ['Sanduíche do Mergulhador', 'Sanduíche do Cais'],
    wrap: ['Wrap das Correntes', 'Wrap do Mergulhador'],
    porcao: ['Petiscos do Cais', 'Porção do Cardume'],
    pastel: ['Pastel do Cais', 'Pastel da Maré'],
    coxinha: ['Coxinha do Cais', 'Coxinha do Recife'],
    pao_de_queijo: ['Pérolas de Pão de Queijo', 'Pão de Queijo do Farol'],
    sushi: ['Sushi do Recife', 'Sushi do Cardume'],
    temaki: ['Temaki do Recife', 'Temaki da Maré'],
    espetinho: ['Espetinho do Cais', 'Espetinho do Pescador'],
    croissant: ['Croissant Concha do Mar', 'Croissant do Farol'],

    bolo: ['Bolo do Recife de Coral', 'Bolo da Sereia'],
    cupcake: ['Cupcake da Sereia', 'Cupcake do Coral'],
    sorvete: ['Sorvete das Águas Geladas', 'Sorvete do Recife'],
    picole: ['Picolé da Praia', 'Picolé da Maré'],
    pudim: ['Pudim da Água-Viva', 'Pudim do Recife'],
    mousse: ['Mousse de Espuma do Mar', 'Mousse na Taça da Sereia'],
    torta: ['Torta do Recife', 'Torta da Sereia'],
    cookie: ['Cookie Bolacha-do-Mar', 'Cookie do Recife'],
    chocolate: ['Chocolate do Baú Afundado', 'Chocolate do Naufrágio'],
    brigadeiro: ['Brigadeiros Pérolas Negras', 'Brigadeiros do Recife'],
    churros: ['Churros do Cais', 'Churros da Praia'],
    waffle: ['Waffle do Farol', 'Waffle do Recife'],
    acai: ['Açaí da Lagoa Azul', 'Açaí do Recife'],
    donut: ['Rosquinha Boia', 'Rosquinha do Recife'],
    fruta: ['Frutas da Ilha do Recife', 'Frutas da Lagoa'],
    generico: ['Tesouro das Profundezas', 'Surpresa da Maré', 'Mistério do Recife'],
  },
  guilda: {
    suco_laranja: ['Poção de Laranja do Aventureiro', 'Suco de Laranja da Guilda'],
    suco_uva: ['Poção de Mana de Uva', 'Suco de Uva da Guilda'],
    suco_limao: ['Limonada do Ladino', 'Poção Cítrica de Limão'],
    suco_morango: ['Poção de Vida de Morango', 'Suco de Morango do Curandeiro'],
    suco_maracuja: ['Poção Calmante de Maracujá', 'Suco de Maracujá do Bardo'],
    suco_abacaxi: ['Suco de Abacaxi da Guilda', 'Poção Tropical de Abacaxi'],
    suco_melancia: ['Poção de Vida de Melancia', 'Suco de Melancia da Taverna da Guilda'],
    suco_manga: ['Suco de Manga do Arqueiro', 'Poção Dourada de Manga'],
    suco_detox: ['Poção de Cura Verde', 'Suco Verde do Druida'],
    refrigerante_cola: ['Refrigerante de Cola da Guilda', 'Cola Borbulhante do Ladino'],
    refrigerante_guarana: ['Guaraná de Vigor', 'Guaraná da Guilda'],
    refrigerante_laranja: ['Refrigerante de Laranja do Bardo', 'Laranja Borbulhante da Guilda'],
    refrigerante_limao: ['Refrigerante de Limão do Arqueiro', 'Limão Borbulhante da Guilda'],
    refrigerante_uva: ['Refrigerante de Uva de Mana', 'Uva Borbulhante da Guilda'],
    energetico: ['Poção de Vigor', 'Energético de Stamina'],
    cha_gelado: ['Chá Gelado do Druida', 'Chá Gelado da Guilda'],
    agua: ['Água do Odre do Aventureiro', 'Água da Fonte da Guilda'],
    agua_gas: ['Água com Gás da Guilda', 'Água Borbulhante do Odre'],
    agua_coco: ['Água de Coco das Terras Distantes', 'Água de Coco do Explorador'],
    cerveja: ['Cerveja da Guilda', 'Caneca do Guerreiro', 'Cerveja da Missão Cumprida'],
    cerveja_escura: ['Cerveja Escura da Masmorra', 'Cerveja Escura do Anão Ferreiro'],
    vinho: ['Vinho do Paladino', 'Vinho do Banquete da Vitória'],
    vinho_branco: ['Vinho Branco dos Elfos', 'Espumante da Vitória'],
    drink: ['Drink do Bardo', 'Coquetel da Guilda', 'Drink do Ladino'],
    caipirinha: ['Caipirinha do Arqueiro', 'Caipirinha da Guilda'],
    cafe: ['Café da Vigília do Paladino', 'Café Forte do Guerreiro'],
    cappuccino: ['Cappuccino do Bardo', 'Cappuccino da Guilda'],
    cha: ['Chá do Druida', 'Chá do Curandeiro'],
    chocolate_quente: ['Chocolate Quente do Acampamento', 'Chocolate Quente da Guilda'],
    milkshake: ['Milkshake do Aprendiz', 'Milkshake da Guilda'],
    smoothie: ['Smoothie do Druida', 'Smoothie de Frutas da Floresta'],
    vitamina: ['Vitamina de Força', 'Vitamina do Guerreiro'],

    hamburguer: ['Hambúrguer do Guerreiro', 'Hambúrguer de Rank S', 'Hambúrguer do Paladino'],
    hotdog: ['Cachorro-quente do Acampamento', 'Cachorro-quente do Ladino'],
    pizza: ['Pizza da Guilda', 'Pizza do Grupo de Aventureiros'],
    batata_frita: ['Batatas Fritas do Acampamento', 'Batatas da Guilda'],
    frango: ['Frango do Caçador', 'Frango Assado da Fogueira'],
    carne: ['Carne do Banquete da Vitória', 'Carne Grelhada do Caçador'],
    peixe: ['Peixe do Lago da Missão', 'Peixe do Pescador da Guilda'],
    camarao: ['Camarões da Missão no Litoral', 'Camarões do Porto da Guilda'],
    salada: ['Salada do Druida', 'Salada da Horta da Guilda'],
    sopa: ['Sopa do Acampamento', 'Caldo Restaurador do Curandeiro'],
    massa: ['Massa da Guilda', 'Massa do Cozinheiro da Guilda'],
    lasanha: ['Lasanha das Camadas da Masmorra', 'Lasanha da Guilda'],
    prato_feito: ['Prato do Aventureiro', 'Refeição de Recompensa'],
    sanduiche: ['Sanduíche de Viagem', 'Sanduíche do Explorador'],
    wrap: ['Wrap da Estrada', 'Wrap do Mensageiro'],
    porcao: ['Petiscos do Grupo', 'Porção da Guilda'],
    pastel: ['Pastel da Estrada', 'Pastel do Mercado da Guilda'],
    coxinha: ['Coxinha do Aprendiz', 'Coxinha da Guilda'],
    pao_de_queijo: ['Pão de Queijo de Viagem', 'Pães de Queijo da Guilda'],
    sushi: ['Sushi do Samurai Errante', 'Sushi das Terras do Leste'],
    temaki: ['Temaki do Samurai Errante', 'Temaki das Terras do Leste'],
    espetinho: ['Espetinho da Fogueira do Acampamento', 'Espetinho do Caçador'],
    croissant: ['Croissant da Padaria da Guilda', 'Croissant do Café da Manhã do Herói'],

    bolo: ['Bolo da Missão Cumprida', 'Bolo da Guilda'],
    cupcake: ['Cupcake de Recompensa', 'Cupcake do Bardo'],
    sorvete: ['Sorvete das Montanhas Geladas', 'Sorvete da Guilda'],
    picole: ['Picolé do Explorador', 'Picolé da Guilda'],
    pudim: ['Pudim da Guilda', 'Pudim do Curandeiro'],
    mousse: ['Mousse na Taça da Vitória', 'Mousse da Guilda'],
    torta: ['Torta da Taverna da Guilda', 'Torta do Banquete da Vitória'],
    cookie: ['Cookie de Viagem', 'Cookie do Aprendiz'],
    chocolate: ['Chocolate do Baú da Masmorra', 'Chocolate de Recompensa'],
    brigadeiro: ['Brigadeiros de Recompensa', 'Brigadeiros da Guilda'],
    churros: ['Churros do Mercado da Guilda', 'Churros do Festival'],
    waffle: ['Waffle do Café da Manhã do Herói', 'Waffle da Guilda'],
    acai: ['Açaí do Druida', 'Açaí da Guilda'],
    donut: ['Rosquinha do Aprendiz', 'Rosquinha da Guilda'],
    fruta: ['Frutas da Floresta', 'Frutas do Mercado da Guilda'],
    generico: ['Recompensa Misteriosa', 'Prato da Guilda', 'Tesouro da Masmorra'],
  },
};
