// Nomes temáticos exibidos abaixo do nome real do produto (na ficha e no carrinho).
// Cada tipo tem uma lista: itens do mesmo tipo no cardápio recebem apelidos diferentes, em sequência.
// Regras: o apelido dá o clima do tema, mas deixa claro o que é o item (de preferência citando-o),
// e não afirma nada que o tipo não garante (ex.: "fruta" não vira "maçã").

export const APELIDOS = {
  bruxo: {
    suco_laranja: ['Poção de Laranja do Sol Nascente', 'Elixir Dourado de Laranja'],
    suco_uva: ['Elixir de Uva do Crepúsculo', 'Poção das Videiras Sombrias'],
    suco_limao: ['Poção Cítrica de Limão', 'Tônico de Limão do Boticário'],
    suco_morango: ['Poção de Morango Encantado', 'Tônico Rubi de Morango'],
    suco_maracuja: ['Poção de Maracujá da Calmaria', 'Elixir de Maracujá do Sono Leve'],
    suco_abacaxi: ['Poção de Abacaxi da Coroa Dourada', 'Elixir Tropical de Abacaxi'],
    suco_melancia: ['Poção de Melancia da Lua Carmesim', 'Tônico Refrescante de Melancia'],
    suco_manga: ['Elixir de Manga do Pôr do Sol', 'Poção Dourada de Manga'],
    suco_detox: ['Poção Verde Purificadora', 'Tônico Verde da Estufa'],
    refrigerante_cola: ['Refresco Borbulhante das Sombras', 'Poção Efervescente da Meia-Noite'],
    refrigerante_guarana: ['Guaraná de Fogo-Fátuo', 'Refresco Âmbar Borbulhante'],
    refrigerante_laranja: ['Refresco de Laranja da Fênix', 'Laranja Efervescente do Entardecer'],
    refrigerante_limao: ['Refresco de Limão Efervescente', 'Limão Borbulhante do Pântano'],
    refrigerante_uva: ['Refresco de Uva Borbulhante', 'Uva Efervescente do Crepúsculo'],
    energetico: ['Poção Energética do Relâmpago', 'Elixir da Vigília Eterna'],
    cha_gelado: ['Chá Gelado da Vidente', 'Infusão Gelada Enfeitiçada'],
    agua: ['Água da Fonte Encantada', 'Água do Lago Cristalino'],
    agua_gas: ['Água Cintilante da Nascente', 'Água Borbulhante Encantada'],
    agua_coco: ['Água do Coqueiro Encantado', 'Água de Coco das Ilhas Mágicas'],
    cerveja: ['Cerveja do Caldeirão', 'Cerveja Espumante do Salão', 'Caneca Espumante do Mago'],
    cerveja_escura: ['Cerveja das Sombras', 'Cerveja Escura do Caldeirão'],
    vinho: ['Vinho da Adega Encantada', 'Vinho do Filtro do Amor'],
    vinho_branco: ['Vinho Pálido da Lua', 'Vinho das Videiras de Prata'],
    drink: ['Drink do Alquimista', 'Coquetel da Festa Encantada', 'Mistura Enfeitiçada'],
    caipirinha: ['Caipirinha do Alquimista', 'Caipirinha Cítrica da Floresta'],
    cafe: ['Café Elixir do Despertar', 'Café Negro da Madrugada'],
    cappuccino: ['Cappuccino Cremoso Encantado', 'Nuvem de Café Encantado'],
    cha: ['Chá da Vidente', 'Chá das Folhas Proféticas'],
    chocolate_quente: ['Cacau Quente contra Calafrios', 'Poção Quente de Chocolate'],
    milkshake: ['Milkshake Nuvem de Fada', 'Milkshake Encantado do Unicórnio'],
    smoothie: ['Smoothie das Frutas Silvestres', 'Poção Batida do Bosque'],
    vitamina: ['Vitamina da Força Matinal', 'Vitamina Revigorante do Pomar'],

    hamburguer: ['Hambúrguer Alado', 'Hambúrguer do Dragão', 'Hambúrguer Enfeitiçado'],
    hotdog: ['Cachorro-quente da Salamandra', 'Cachorro-quente Flamejante'],
    pizza: ['Pizza Rúnica', 'Pizza do Forno Encantado'],
    batata_frita: ['Batatas do Caldeirão', 'Fritas Encantadas'],
    frango: ['Frango do Grifo', 'Frango Encantado'],
    carne: ['Carne do Banquete Encantado', 'Carne Grelhada do Salão'],
    peixe: ['Peixe do Lago Encantado', 'Peixe do Lago Escuro'],
    camarao: ['Camarões do Lago das Sereias', 'Camarões Encantados'],
    salada: ['Salada da Estufa Mágica', 'Salada de Ervas da Estufa'],
    sopa: ['Caldo do Caldeirão Mirim', 'Sopa Borbulhante'],
    massa: ['Massa Enfeitiçada', 'Massa do Caldeirão'],
    lasanha: ['Lasanha das Mil Camadas', 'Lasanha do Forno Encantado'],
    prato_feito: ['Prato do Salão Principal', 'Prato do Aprendiz de Feiticeiro'],
    sanduiche: ['Sanduíche do Aprendiz', 'Sanduíche Enfeitiçado'],
    wrap: ['Wrap Enrolado como Pergaminho', 'Rolo Recheado do Escriba'],
    porcao: ['Petiscos do Caldeirão', 'Porção do Alquimista'],
    pastel: ['Pastel Encantado', 'Pastel do Caldeirão'],
    coxinha: ['Coxinha Encantada', 'Coxinha do Caldeirão'],
    pao_de_queijo: ['Pães de Queijo Encantados', 'Pão de Queijo do Forno Mágico'],
    sushi: ['Sushi do Lago Encantado', 'Sushi do Mestre das Águas'],
    temaki: ['Temaki Enfeitiçado', 'Cone de Alga Encantado'],
    espetinho: ['Espetinho da Varinha', 'Espetinho do Mago'],
    croissant: ['Croissant da Lua Crescente', 'Croissant Folhado Encantado'],

    bolo: ['Bolo das Velas Eternas', 'Bolo Enfeitiçado'],
    cupcake: ['Cupcake da Fada Madrinha', 'Cupcake Enfeitiçado'],
    sorvete: ['Sorvete Enfeitiçado', 'Sorvete das Neves Eternas'],
    picole: ['Picolé Enfeitiçado', 'Picolé Congelado por Feitiço'],
    pudim: ['Pudim Levitante', 'Pudim Flutuante do Salão'],
    mousse: ['Mousse Encantada na Taça', 'Mousse Nuvem Doce'],
    torta: ['Torta do Salão Encantado', 'Torta Enfeitiçada'],
    cookie: ['Cookie Estelar', 'Cookie das Estrelas'],
    chocolate: ['Chocolate Enfeitiçado', 'Doce de Cacau do Boticário'],
    brigadeiro: ['Brigadeiros Encantados', 'Docinhos do Caldeirão'],
    churros: ['Churros do Mago', 'Churros Encantados'],
    waffle: ['Waffle do Castelo', 'Waffle Dourado Encantado'],
    acai: ['Açaí do Bosque Encantado', 'Açaí Roxo da Floresta'],
    donut: ['Rosquinha Encantada', 'Rosquinha Anel de Fada'],
    fruta: ['Frutas da Árvore Encantada', 'Frutas do Pomar Mágico'],
    generico: ['Mistério Encantado', 'Prato Enfeitiçado', 'Surpresa do Caldeirão'],
  },

  medieval: {
    suco_laranja: ['Suco de Laranja do Pomar Real', 'Néctar de Laranja do Castelo'],
    suco_uva: ['Suco de Uva do Vale', 'Suco da Vinha do Mosteiro'],
    suco_limao: ['Limonada do Boticário', 'Refresco de Limão da Corte'],
    suco_morango: ['Néctar de Morangos Silvestres', 'Suco de Morango da Donzela'],
    suco_maracuja: ['Néctar de Maracujá das Terras do Sul', 'Suco de Maracujá do Mercador'],
    suco_abacaxi: ['Suco de Abacaxi do Pomar Real', 'Néctar de Abacaxi do Mercador'],
    suco_melancia: ['Suco de Melancia da Colheita', 'Refresco de Melancia do Horto'],
    suco_manga: ['Néctar de Manga do Mercador', 'Suco de Manga das Terras do Sul'],
    suco_detox: ['Suco Verde do Herbalista', 'Suco Verde do Mosteiro'],
    refrigerante_cola: ['Refresco Borbulhante Escuro', 'Borbulha Negra da Taverna'],
    refrigerante_guarana: ['Guaraná Borbulhante da Taverna', 'Refresco Borbulhante Dourado'],
    refrigerante_laranja: ['Refresco Borbulhante de Laranja', 'Laranja Borbulhante do Pomar'],
    refrigerante_limao: ['Refresco Borbulhante de Limão', 'Limão Borbulhante da Corte'],
    refrigerante_uva: ['Refresco Borbulhante de Uva', 'Uva Borbulhante do Rei'],
    energetico: ['Elixir do Cavaleiro Incansável', 'Tônico Energético do Guarda Noturno'],
    cha_gelado: ['Chá Gelado do Poço', 'Chá Frio do Herbalista'],
    agua: ['Água da Fonte do Castelo', 'Água do Poço Real'],
    agua_gas: ['Água da Fonte Borbulhante', 'Água Borbulhante das Termas'],
    agua_coco: ['Água de Coco dos Navegantes', 'Água do Fruto das Ilhas'],
    cerveja: ['Cerveja do Mosteiro', 'Caneca de Cerveja do Taverneiro', 'Cerveja da Guilda'],
    cerveja_escura: ['Cerveja Escura do Ferreiro', 'Caneca de Cerveja Negra'],
    vinho: ['Vinho da Adega Real', 'Taça de Vinho do Rei'],
    vinho_branco: ['Vinho Claro da Abadia', 'Taça Dourada da Rainha'],
    drink: ['Chifre do Guerreiro', 'Drink do Bardo', 'Mistura da Taverna'],
    caipirinha: ['Caipirinha do Marinheiro', 'Caipirinha do Engenho'],
    cafe: ['Café Negro do Vigia', 'Café da Sentinela'],
    cappuccino: ['Café com Nata do Vigia', 'Cappuccino da Sentinela'],
    cha: ['Chá do Herbalista', 'Chá das Ervas do Mosteiro'],
    chocolate_quente: ['Chocolate Quente do Mercador', 'Cacau Quente das Terras Distantes'],
    milkshake: ['Milkshake da Leiteira', 'Leite Batido da Fazenda'],
    smoothie: ['Batida de Frutas do Bosque', 'Smoothie das Frutas Silvestres'],
    vitamina: ['Vitamina do Camponês', 'Vitamina do Lavrador'],

    hamburguer: ['Hambúrguer do Torneio', 'Hambúrguer do Escudeiro', 'Lanche do Cavaleiro'],
    hotdog: ['Cachorro-quente da Feira', 'Salsicha do Açougueiro no Pão'],
    pizza: ['Pizza do Forno a Lenha', 'Pizza do Forno do Castelo'],
    batata_frita: ['Batatas Fritas da Taverna', 'Batatas da Colheita'],
    frango: ['Frango do Galinheiro Real', 'Frango do Banquete'],
    carne: ['Carne do Braseiro Real', 'Carne Grelhada do Banquete'],
    peixe: ['Peixe do Rio do Castelo', 'Peixe do Porto da Vila'],
    camarao: ['Camarões do Porto', 'Frutos do Mar do Mercador'],
    salada: ['Salada da Horta', 'Folhas do Jardim do Mosteiro'],
    sopa: ['Caldo Quente da Estalagem', 'Sopa do Caldeirão da Taverna'],
    massa: ['Massa do Mercador', 'Massa do Moinho'],
    lasanha: ['Lasanha do Forno de Pedra', 'Lasanha da Abadia'],
    prato_feito: ['Refeição do Camponês', 'Prato do Viajante'],
    sanduiche: ['Sanduíche do Moleiro', 'Sanduíche do Peregrino'],
    wrap: ['Pão Enrolado do Viajante', 'Rolo Recheado do Mensageiro'],
    porcao: ['Petiscos da Taverna', 'Porção da Guilda'],
    pastel: ['Pastel da Feira', 'Empanada do Peregrino'],
    coxinha: ['Coxinha da Feira da Vila', 'Coxinha do Padeiro'],
    pao_de_queijo: ['Pão de Queijo do Forno de Pedra', 'Pãezinhos de Queijo da Fazenda'],
    sushi: ['Sushi do Mercador Oriental', 'Sushi das Terras do Leste'],
    temaki: ['Temaki do Mercador Oriental', 'Cone de Alga das Terras do Leste'],
    espetinho: ['Espetinho da Fogueira', 'Espeto do Ferreiro'],
    croissant: ['Croissant do Padeiro Real', 'Croissant Folhado da Corte'],

    bolo: ['Bolo da Festa da Colheita', 'Bolo do Banquete Real'],
    cupcake: ['Cupcake da Princesa', 'Bolinho Confeitado da Feira'],
    sorvete: ['Sorvete da Montanha Nevada', 'Sorvete do Inverno'],
    picole: ['Picolé do Inverno', 'Picolé do Mercador'],
    pudim: ['Pudim do Mosteiro', 'Pudim da Abadia'],
    mousse: ['Mousse da Corte na Taça', 'Taça de Mousse da Rainha'],
    torta: ['Torta da Colheita', 'Torta do Forno de Pedra'],
    cookie: ['Biscoito do Padeiro Real', 'Cookie do Peregrino'],
    chocolate: ['Doce de Cacau do Mercador', 'Chocolate do Tesouro Real'],
    brigadeiro: ['Brigadeiros da Corte', 'Docinhos do Tesouro Real'],
    churros: ['Churros da Feira', 'Churros do Festival'],
    waffle: ['Waffle do Padeiro Real', 'Waffle da Padaria do Castelo'],
    acai: ['Açaí do Bosque', 'Tigela de Açaí Selvagem'],
    donut: ['Rosquinha da Feira', 'Rosca Açucarada da Padaria'],
    fruta: ['Frutas do Pomar Real', 'Cesta de Frutas da Colheita'],
    generico: ['Surpresa do Taverneiro', 'Prato da Casa', 'Segredo da Cozinha'],
  },

  futurista: {
    suco_laranja: ['Cápsula de Laranja C-12', 'Suco de Laranja Concentrado'],
    suco_uva: ['Cápsula de Uva V-7', 'Suco de Uva Hidropônica'],
    suco_limao: ['Cápsula de Limão L-3', 'Limonada de Estufa Orbital'],
    suco_morango: ['Cápsula de Morango R-9', 'Suco de Morango Sintético'],
    suco_maracuja: ['Cápsula de Maracujá M-5', 'Suco de Maracujá Calmante'],
    suco_abacaxi: ['Cápsula de Abacaxi T-4', 'Suco de Abacaxi de Estufa'],
    suco_melancia: ['Cápsula de Melancia H-8', 'Suco de Melancia Hidratante'],
    suco_manga: ['Cápsula de Manga A-6', 'Suco de Manga Orbital'],
    suco_detox: ['Cápsula Verde Detox D-1', 'Suco Verde Biorregenerador'],
    refrigerante_cola: ['Neo Cola Gravidade Zero', 'Cola Quântica'],
    refrigerante_guarana: ['Guaraná Quântico', 'Guaraná Iônico'],
    refrigerante_laranja: ['Laranja Fizz de Plasma', 'Refri de Laranja Orbital'],
    refrigerante_limao: ['Limão Fizz Iônico', 'Refri de Limão Neon'],
    refrigerante_uva: ['Uva Fizz Nebular', 'Refri de Uva Iônico'],
    energetico: ['Energético Carga de Reator', 'Bateria Líquida Mk III'],
    cha_gelado: ['Chá Gelado Criogênico', 'Chá Resfriado a Nitrogênio'],
    agua: ['Água Filtrada de Cometa', 'Água de Degelo Polar'],
    agua_gas: ['Água Ionizada com Gás', 'Água Gaseificada Orbital'],
    agua_coco: ['Água de Coco de Estufa', 'Água de Coco Hidratante'],
    cerveja: ['Cerveja Orbital', 'Cerveja de Estação Espacial'],
    cerveja_escura: ['Cerveja de Matéria Escura', 'Cerveja Buraco Negro'],
    vinho: ['Vinho Sintético Safra 2199', 'Vinho Fermentado em Órbita'],
    vinho_branco: ['Vinho Branco de Estufa Lunar', 'Espumante Safra 2199'],
    drink: ['Drink Nebulosa Líquida', 'Coquetel de Hiperespaço', 'Drink Estelar'],
    caipirinha: ['Caipirinha Supernova', 'Caipirinha Estelar'],
    cafe: ['Café Hiperpropulsão', 'Café Combustível de Piloto'],
    cappuccino: ['Cappuccino Hiperpropulsão', 'Nuvem de Café Pressurizada'],
    cha: ['Chá Bioluminescente', 'Chá de Estufa Orbital'],
    chocolate_quente: ['Chocolate Termonuclear', 'Cacau Aquecido a Plasma'],
    milkshake: ['Milkshake Criogênico', 'Milkshake Gravidade Zero'],
    smoothie: ['Smoothie de Frutas Replicadas', 'Smoothie Bioativo'],
    vitamina: ['Vitamina Matinal Mk I', 'Vitamina Nutritiva de Bordo'],

    hamburguer: ['Burger Holográfico Mk II', 'Burger Replicado', 'Hambúrguer de Proteína Cultivada'],
    hotdog: ['Cachorro-quente de Plasma', 'Hot Dog de Fusão'],
    pizza: ['Pizza Replicada', 'Pizza do Forno de Plasma'],
    batata_frita: ['Batatas Fritas Hidropônicas', 'Bastões de Batata Crocante'],
    frango: ['Frango Cultivado em Laboratório', 'Frango Grelhado a Laser'],
    carne: ['Carne Grelhada a Laser', 'Corte Premium Cultivado'],
    peixe: ['Peixe do Aquário Orbital', 'Peixe de Biotanque'],
    camarao: ['Camarões do Biotanque', 'Frutos do Mar Orbitais'],
    salada: ['Salada Hidropônica', 'Mix de Folhas de Estufa'],
    sopa: ['Caldo Térmico', 'Sopa Pressurizada'],
    massa: ['Massa Replicada', 'Massa Extrudada Orbital'],
    lasanha: ['Lasanha Impressa em Camadas', 'Lasanha Gratinada a Plasma'],
    prato_feito: ['Refeição Completa de Tripulante', 'Prato Executivo de Bordo'],
    sanduiche: ['Sanduíche de Bordo', 'Módulo Sanduíche'],
    wrap: ['Wrap de Bordo', 'Wrap Nutritivo Selado'],
    porcao: ['Kit Petisco Tático', 'Porção da Tripulação'],
    pastel: ['Pastel Selado a Vácuo', 'Pastel Crocante Pressurizado'],
    coxinha: ['Coxinha Mk I', 'Coxinha Crocante Orbital'],
    pao_de_queijo: ['Pão de Queijo Aquecido a Plasma', 'Orbes de Pão de Queijo'],
    sushi: ['Kit Sushi de Bordo', 'Sushi de Biotanque'],
    temaki: ['Temaki em Cone Selado', 'Temaki Orbital'],
    espetinho: ['Espetinho de Íons', 'Espetinho Grelhado a Laser'],
    croissant: ['Croissant de Impressão Folhada', 'Croissant Laminado Orbital'],

    bolo: ['Bolo Gravitacional', 'Bolo em Camadas Estabilizadas'],
    cupcake: ['Cupcake de Órbita Baixa', 'Micro-Bolo Decorado'],
    sorvete: ['Sorvete Criogênico', 'Sorvete de Nitrogênio Líquido'],
    picole: ['Picolé Criogênico', 'Picolé de Órbita Polar'],
    pudim: ['Pudim Estabilizado', 'Pudim de Gravidade Controlada'],
    mousse: ['Mousse Pressurizada', 'Mousse Aerada de Bordo'],
    torta: ['Torta de Estufa Lunar', 'Torta do Forno de Plasma'],
    cookie: ['Cookie Asteroide', 'Cookie de Cratera'],
    chocolate: ['Lingotes de Chocolate', 'Barras de Energia de Cacau'],
    brigadeiro: ['Brigadeiros Planetários', 'Esferas de Chocolate Orbitais'],
    churros: ['Churros Extrudados', 'Churros de Açúcar Iônico'],
    waffle: ['Waffle Térmico', 'Waffle Painel Solar'],
    acai: ['Açaí Nebular', 'Açaí Energético'],
    donut: ['Rosquinha de Saturno', 'Rosquinha Anel Orbital'],
    fruta: ['Frutas Hidropônicas', 'Frutas da Estufa Orbital'],
    generico: ['Ração Misteriosa', 'Item Não Identificado', 'Refeição Padrão de Bordo'],
  },
};
